In [29]:
# 1. How can you concatenate two tuples?

In [30]:
tup1 = (1, "a", True)
tup2 = (4,5,6)

tup1 + tup2

(1, 'a', True, 4, 5, 6)

In [31]:
# 2. how can you initialize 5x5 Numpy array with only zeroes?

In [32]:
import numpy as np

np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
#3. what is pandas series?

import pandas as pd

data = ['1', 2, 'three', 4.0]

series = pd.Series(data)

series

0        1
1        2
2    three
3      4.0
dtype: object

In [34]:
print(type(series))

<class 'pandas.core.series.Series'>


In [35]:
#4. what is the use of pandas groupby function?

df = pd.DataFrame({'vehicle': ['Kia', 'Lamborghini', 'KTM', 'pulsar'], 
                    'type' : ['car', 'car', 'motorcycle', 'motorcycle']})

df

vehicle        type
0          Kia         car
1  Lamborghini         car
2          KTM  motorcycle
3       pulsar  motorcycle

In [36]:
df.groupby('type').count()

vehicle
type               
car               2
motorcycle        2

In [37]:
#5. how to create dataframe from lists?

df = pd.DataFrame()

names = ["Pooja", "Krupa", "Shree", "Ankita"]

age = [20, 25, 22, 15] 

df['names'] = names
df['age'] = age

df

names  age
0   Pooja   20
1   Krupa   25
2   Shree   22
3  Ankita   15

In [38]:
#6. how to create dataFrame from a dictionary?

df = pd.DataFrame()

names = ["Pooja", "Krupa", "Shree", "Ankita"]

age = [20, 25, 22, 15] 

d = {"names" : names, "age" : age}

df = pd.DataFrame(d)

df

names  age
0   Pooja   20
1   Krupa   25
2   Shree   22
3  Ankita   15

In [39]:
# Given a dataframe, how do you drop all rows having NaN?

# df.dropna()

In [40]:

#7. how to access data from a dataframe using a value as index?

df = pd.DataFrame()

names = ["Pooja", "Krupa", "Shree", "Ankita"]

age = [20, 25, 22, 15] 

d = {"names" : names, "age" : age}

df = pd.DataFrame(d)

a = [10, 20, 30, 40]

df.index = a

df

names  age
10   Pooja   20
20   Krupa   25
30   Shree   22
40  Ankita   15

In [41]:
df.loc[10]

names    Pooja
age         20
Name: 10, dtype: object

In [42]:
#8. what is the most memory-efficient way to add elements to a tuple?

# Tuples are immutable datatypes in Python

# you cannot add elements to an existing tuple

# A new one must be created if the values are to be changed


In [43]:
#9. find out the measures  of central tendency for this Numpy array: np.array([1,5,3,100,4,48])

n1 = np.array([1,5,3,100,4,48])

print(np.mean(n1))

print(np.median(n1))

print(np.std(n1))


26.833333333333332
4.5
36.59424666377065


In [44]:
#10.

string = "BeautiFUl LADY"
string.lower()

'beautiful lady'

In [45]:
#11. how will you remove duplicate elements from a list?

my_list = ["a", "c", "c" ,"y" ,"y", "z", "a"]

a = set(my_list)

a

{'a', 'c', 'y', 'z'}

In [46]:
#12. how will you remove duplicate elements from a list?

alphabets = ["a", "c", "c" ,"y" ,"y", "z", "a"]

alphabets = list(dict.fromkeys(alphabets))

print(alphabets)

['a', 'c', 'y', 'z']


In [47]:
#13. explain python list comprehension

my_list = [i for i in range(10)]
print(my_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [48]:
#14. what is a map function in python?

def add_func(n):
    return n * 3

num = (1,2,3,4,5,6)  # iterable is a tuple

result = map(add_func, num)

list(result)

[3, 6, 9, 12, 15, 18]

In [49]:
#15. what is a map function in python?

def add_function(n):
    return n * 5

num = [1,2,3,4,5]   # iterable is a list

result = list(map(add_function, num))

result

[5, 10, 15, 20, 25]

In [50]:
# 16. what is __init__ in python?

# reserved method, constructor.
# when an object is created from a class, the __init__methodology is called to access the class attributes.


In [51]:
#17. How to create a new column in pandas using values from other columns 

a = [1,3,4]

b = [4,5,6]

d = {'a' : a, 'b' : b}

df = pd.DataFrame(d)

df['product'] = df['a'] * df['b']   # new column

df

a  b  product
0  1  4        4
1  3  5       15
2  4  6       24

In [52]:
df = pd.DataFrame()

c = [1,3,4]

d = [4,5,6]

df['c'] = c
df['d'] = d

df['product'] = df['c'] * df['d']

df

c  d  product
0  1  4        4
1  3  5       15
2  4  6       24

In [53]:
#18. how can an object be copied in python?

# we use = operator to create a copy of an object.

old_list = [1,2,3,4,"a"]

new_list = old_list

print(old_list)

print(new_list)

[1, 2, 3, 4, 'a']
[1, 2, 3, 4, 'a']


In [54]:
#19. what is split function used for?

letter = "Good-Morning"

print(letter.split("-"))

['Good', 'Morning']


In [55]:
#20. what is docstring in python?

str.__doc__

"str(object='') -> str\nstr(bytes_or_buffer[, encoding[, errors]]) -> str\n\nCreate a new string object from the given object. If encoding or\nerrors is specified, then the object must expose a data buffer\nthat will be decoded using the given encoding and error handler.\nOtherwise, returns the result of object.__str__() (if defined)\nor repr(object).\nencoding defaults to sys.getdefaultencoding().\nerrors defaults to 'strict'."

In [56]:
print.__doc__

"print(value, ..., sep=' ', end='\\n', file=sys.stdout, flush=False)\n\nPrints the values to a stream, or to sys.stdout by default.\nOptional keyword arguments:\nfile:  a file-like object (stream); defaults to the current sys.stdout.\nsep:   string inserted between values, default a space.\nend:   string appended after the last value, default a newline.\nflush: whether to forcibly flush the stream."

In [57]:
#21. what is the use of Lambda function in Python?

triple = lambda x: x*3

triple(100)

300

In [58]:
#22. how do you find the factorial of a number using recursion?

def factorial(n):
    if n == 1:
        return 1
    else:
        return (n * factorial(n-1))

In [59]:
factorial(5)

120

In [60]:
#23. how do you find the factorial of a number using recursion?

n = int(input("Enter any number: "))

def factorial(n):
    if n == 1:
        return 1
    else:
        return (n * factorial(n-1))
    
print("factorial of", n ,"is", factorial(n))

Enter any number: 25
factorial of 25 is 15511210043330985984000000


In [61]:
#24. can you denote the working of the bool() function with examples?

a = "hello"
b = 15
c = 0
sample_list = []
p = None

print(bool(a))
print(bool(b))
print(bool(c))
print(bool(sample_list))
print(bool(p))


True
True
False
False
False


In [62]:
#25. how to delete a column or group of columns in pandas?

d = {"col 1" : [1,2,3] , "col 2" : [4,5,6]}

df = pd.DataFrame(d)

df

col 1  col 2
0      1      4
1      2      5
2      3      6

In [63]:
df.drop(['col 1'], axis = 1)

col 2
0      4
1      5
2      6

In [64]:
#26. what is reindexing in pandas?

d = {"fruits" : ["apple", "mango", "banana", "cherry"] , "cost" : [100, 200, 300, 400]}

df = pd.DataFrame(d)

print(df)

a = [10,20,30,40]

df.index = a

df

   fruits  cost
0   apple   100
1   mango   200
2  banana   300
3  cherry   400


fruits  cost
10   apple   100
20   mango   200
30  banana   300
40  cherry   400

In [65]:
#27. create a lambda function which will print the sum of all the elements in the list

from functools import reduce

a = [5, 8, 10, 20, 50, 100]

sum = reduce(lambda x, y: x+y, a)

sum

193

In [66]:
# 28.

n1 = np.array([10,20,30,40])
n2 = np.array([50,60,70,80])

print(np.vstack((n1,n2)))

[[10 20 30 40]
 [50 60 70 80]]


In [67]:
list_1 = [1,2,3]
list_1

[1, 2, 3]

In [68]:
# 29.

list_1 * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [69]:
# 30.
list_2= []
for i in list_1:
    list_2.append(i*3)
list_2

[3, 6, 9]

In [70]:
# 31.

list_2 = list(map(lambda x: x*3, list_1))
list_2

[3, 6, 9]

In [71]:
#32. convert a string to dictionary 

In [72]:
name = "Siddhi"
num = range(1,7)

dict_ = dict(zip(num,name))
dict_

{1: 'S', 2: 'i', 3: 'd', 4: 'd', 5: 'h', 6: 'i'}

In [73]:
name = "siddhi"
dict_ = dict(zip(range(6), name))
dict_

{0: 's', 1: 'i', 2: 'd', 3: 'd', 4: 'h', 5: 'i'}

In [74]:
#33. find the common letters between 2 strings

In [75]:
string_1 = "naina"
string_2 = "Reene"

In [76]:
set(string_1).intersection(set(string_2))

{'n'}

In [77]:
def common_letters(string_1, string_2):
    return set(string_1).intersection(set(string_2))

In [78]:
common_letters("naina", "Reene")

{'n'}

In [79]:
# 34.

def common_letters():
    str1= input("enter 1st string: ")
    str2= input("enter 2nd string: ")
    s1 = set(str1)
    s2 = set(str2)
    print(s1)
    print(s2)
    common = s1 & s2
    print(common)
    

In [80]:
common_letters()

enter 1st string: siddhi
enter 2nd string: vinit
{'h', 'd', 's', 'i'}
{'t', 'n', 'v', 'i'}
{'i'}


In [81]:
#35. count the frequency of words appearing in a string

In [82]:
string = "Sheena loves eating apple and mango. her sister also loves eating apple and mango."

In [83]:
from collections import Counter

Counter(string.split(" "))

Counter({'Sheena': 1,
         'loves': 2,
         'eating': 2,
         'apple': 2,
         'and': 2,
         'mango.': 2,
         'her': 1,
         'sister': 1,
         'also': 1})

In [84]:
def freq_words():
    string = input("enter a string: ")
    words = string.split(" ")
    d = {}
    
    for word in words:
        if word not in d.keys():
            d[word] = 0
        d[word] = d[word] + 1
    print(d)
        

In [85]:
freq_words()

enter a string: i live in mumbai i live in india
{'i': 2, 'live': 2, 'in': 2, 'mumbai': 1, 'india': 1}


In [86]:
#36. how can you concatenate 2 list:

list_1 = [1,2,3]
list_2 = [4,5,6]

list_1 + list_2

[1, 2, 3, 4, 5, 6]

In [87]:
# 37. Count the frequency of numbers

# method 1

from collections import Counter
num = [1,2,2,3,4,7,77,77,8,8,8,3,4,5]

Counter(sorted(num))

Counter({1: 1, 2: 2, 3: 2, 4: 2, 5: 1, 7: 1, 8: 3, 77: 2})

In [88]:
# method 2

num = [1,2,2,3,4,7,77,77,8,8,8,3,4,5]

d = {}
for number in sorted(num):
    if number not in d.keys():
        d[number] = 0
    d[number] = d[number] + 1
print(d)

{1: 1, 2: 2, 3: 2, 4: 2, 5: 1, 7: 1, 8: 3, 77: 2}


In [89]:
# 38.Convert 2 lists into a dictionary

list_1 = [1,2,3]
list_2 = ["cat", "dog", "fish"]

dict_ = dict(zip(list_1,list_2))

dict_

{1: 'cat', 2: 'dog', 3: 'fish'}

In [90]:
type(dict_)

dict

In [91]:
# 39. convert dict to tuple

dict_ = {1: 'cat', 2: 'dog', 3: 'fish'}

for item in dict_.items():
    print(item)

(1, 'cat')
(2, 'dog')
(3, 'fish')


In [92]:
# 41. find out pairs with given sum value of an array

arr = [5,7,4,3,9,8,19,21]
sum_arr = 17

sorted(arr)

[3, 4, 5, 7, 8, 9, 19, 21]

In [95]:
# Method 1

def find_pairs(arr,sum_arr):
    array = sorted(arr)
    left = 0
    right = len(array)-1
    
    while(left<right):
        if array[left] + array[right] > sum_arr:
            right = right - 1
        elif array[left] + array[right] < sum_arr:
            left = left + 1
        elif array[left] + array[right] == sum_arr:
            print("values of pair are: ", array[left],"and",array[right])
            right = right -1
            left = left +1

In [96]:
find_pairs([5,7,4,3,9,8,19,21], 27)

values of pair are:  8 and 19


In [24]:
# 41. find out pairs with given sum value of an array

arr = [5,7,4,3,9,8,19,21]
target = 37

In [25]:
def two_sum(arr,target):
    array = sorted(arr)
    left = 0
    right = len(array)-1
    
    while (left < right):
        sum_two = array[left] + array[right]
        if sum_two == target:
            return "Pairs found {} and {}".format(array[left], array[right])
        elif sum_two < target:
            left = left + 1
        elif sum_two > target:
            right = right - 1 
    return "No pairs found"
            

In [26]:
two_sum(arr,target)

'No pairs found'

In [35]:
arr = [5,7,4,3,9,8,19,21]
target = 7

In [36]:
# 42. find out pairs with given sum value of an array with its index

def two_sum(arr, target):
    array = sorted(arr)
    left = 0
    right = len(array) - 1
    
    while(left < right):
        sum_two = array[left] + array[right]
        if sum_two == target:
            return "Pairs found {} and {}, index({},{})".format(array[left], array[right], left,right)
        elif sum_two < target:
            left = left + 1
        elif sum_two > target:
            right = right - 1
            
    return "No Pairs found"


In [37]:
two_sum(arr, target)

'Pairs found 3 and 4, index(0,1)'

In [ ]:
# 43